# Generated by Django 5.1.4 on 2025-02-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reformas_ejer09', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoreforma',
            name='vivienda',
        ),
        migrations.RemoveField(
            model_name='vivienda',
            name='cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='correo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ProyectoReforma',
        ),
        migrations.DeleteModel(
            name='Vivienda',
        ),
    ]
