# Generated by Django 5.1.4 on 2025-02-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reformas_ejer09', '0002_remove_proyectoreforma_vivienda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_cliente',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
