# Generated by Django 5.1.4 on 2025-02-10 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reformas_ejer09', '0006_vivienda_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoDeReforma',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('id_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='Reformas_ejer09.vivienda')),
            ],
        ),
    ]
